version: 2
updates:
  - package-ecosystem: "uv"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3
    labels:
      - "dependencies"
    ignore:
      - dependency-name: "pandas"
        versions:
          - ">=3.0"
