"""TuShare provider implementation for A-share market assets.

This module is now a thin re-export shell over the split provider submodules:
``_env`` (credentials), ``_io`` (IO), ``_frame`` (frame normalization),
``_client`` (runtime client), and ``_adapters`` (business mirrors).
"""

from __future__ import annotations

import time

from market_data_platform.providers._adapters import (
    EVENT_DATE_DEFAULT_FIELDS,
    EVENT_DATE_REQUIRED_FIELDS,
    OptionsT,
    _coerce_options,
    _FundPortfolioPeriodRequest,
    _request_policy,
    _request_policy_from_options,
    _request_policy_payload,
    _tushare_runtime,
    export_a_share_instruments,
    mirror_a_share_adj_factor,
    mirror_a_share_broker_recommend,
    mirror_a_share_daily,
    mirror_a_share_daily_basic,
    mirror_a_share_date_range_event_dataset,
    mirror_a_share_dc_concept,
    mirror_a_share_dc_concept_cons,
    mirror_a_share_fund_portfolio,
    mirror_a_share_hsgt_top10,
    mirror_a_share_index_daily,
    mirror_a_share_kpl_concept_cons,
    mirror_a_share_kpl_list,
    mirror_a_share_limit_cpt_list,
    mirror_a_share_limit_list_ths,
    mirror_a_share_limit_status,
    mirror_a_share_limit_step,
    mirror_a_share_margin,
    mirror_a_share_margin_detail,
    mirror_a_share_moneyflow,
    mirror_a_share_moneyflow_dc,
    mirror_a_share_moneyflow_hsgt,
    mirror_a_share_moneyflow_ths,
    mirror_a_share_month_dataset,
    mirror_a_share_report_rc,
    mirror_a_share_stk_auction_close,
    mirror_a_share_stk_auction_open,
    mirror_a_share_stk_holdertrade,
    mirror_a_share_stk_surv,
    mirror_a_share_ths_hot,
    mirror_a_share_ths_index,
    mirror_a_share_ths_member,
    mirror_a_share_top10_floatholders,
    mirror_a_share_top10_holder_dataset,
    mirror_a_share_top10_holders,
    mirror_a_share_top_inst,
    mirror_a_share_trade_cal,
    mirror_a_share_trade_date_dataset,
    mirror_etf_adj_factor,
    mirror_etf_daily,
    request_policy,
    request_policy_from_options,
    request_policy_payload,
)
from market_data_platform.providers._client import (
    _call_tushare_api,
    _configure_tushare_client_api_url,
    _is_daily_quota_exhausted,
    _pandas,
    _redact_error,
    get_tushare_client,
    verify_tushare_tokens,
)
from market_data_platform.providers._env import (
    _load_tushare_env_files,
    resolve_tushare_api_url,
)
from market_data_platform.providers._frame import _normalize_ts_code
from market_data_platform.providers._io import (
    _fields_text,
    _write_frame,
    _write_manifest,
)
from market_data_platform.providers.tushare_a_share_dates import (
    _validate_date,
)
from market_data_platform.providers.tushare_a_share_options import (
    DEFAULT_ADJ_FACTOR_FIELDS,
    DEFAULT_API_URL_ENV,
    DEFAULT_BROKER_RECOMMEND_FIELDS,
    DEFAULT_DAILY_BASIC_FIELDS,
    DEFAULT_DAILY_FIELDS,
    DEFAULT_DC_CONCEPT_CONS_FIELDS,
    DEFAULT_DC_CONCEPT_FIELDS,
    DEFAULT_DISABLE_PROXY,
    DEFAULT_FUND_ADJ_FIELDS,
    DEFAULT_FUND_DAILY_FIELDS,
    DEFAULT_FUND_PORTFOLIO_FIELDS,
    DEFAULT_KPL_CONCEPT_CONS_FIELDS,
    DEFAULT_KPL_LIST_FIELDS,
    DEFAULT_LIMIT_CPT_LIST_FIELDS,
    DEFAULT_LIMIT_STATUS_FIELDS,
    DEFAULT_LIMIT_STEP_FIELDS,
    DEFAULT_LIST_STATUSES,
    DEFAULT_MONEYFLOW_DC_FIELDS,
    DEFAULT_MONEYFLOW_FIELDS,
    DEFAULT_MONEYFLOW_HSGT_FIELDS,
    DEFAULT_QUOTA_COOLDOWN_SECONDS,
    DEFAULT_REPORT_RC_FIELDS,
    DEFAULT_REQUEST_ATTEMPTS,
    DEFAULT_RETRY_MAX_SLEEP_SECONDS,
    DEFAULT_RETRY_SLEEP_SECONDS,
    DEFAULT_STK_AUCTION_FIELDS,
    DEFAULT_STK_HOLDERTRADE_FIELDS,
    DEFAULT_STK_SURV_FIELDS,
    DEFAULT_STOCK_BASIC_FIELDS,
    DEFAULT_THS_HOT_FIELDS,
    DEFAULT_THS_INDEX_FIELDS,
    DEFAULT_THS_MEMBER_FIELDS,
    DEFAULT_TOKEN_ENV_KEYS,
    DEFAULT_TOP10_HOLDER_FIELDS,
    DEFAULT_TOP_INST_FIELDS,
    DEFAULT_TRADE_DATE_FIELDS,
    NO_PROXY_ENV_KEYS,
    PROXY_ENV_KEYS,
    TRADE_DATE_APIS,
    TRADE_DATE_DEFAULT_REQUEST_OPTIONS,
    TRADE_DATE_REQUIRED_FIELDS,
    DateRangeEventMirrorOptions,
    FundPortfolioMirrorOptions,
    IndexDailyMirrorOptions,
    MonthMirrorOptions,
    StkHoldertradeMirrorOptions,
    Top10HolderMirrorOptions,
    TradeDateMirrorOptions,
    TushareRequestPolicy,
)
from market_data_platform.providers.tushare_a_share_ths_member import (
    ThsMemberMirrorDependencies,
    ThsMemberMirrorOptions,
    mirror_a_share_ths_member_impl,
)
